databases:
  - name: productdb
    databaseName: fastapi_todo
    user: postgres
    plan: free

services:
  - type: web
    name: fastapi-product-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: productdb
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13"
